name: Portfolio CI/CD
run-name: Running portfolio CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
      - name: Install dependencies
        run: npm ci
      - name: Build the page
        run: npm run build
  build-and-deploy:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
      - name: Install dependencies
        run: npm ci
      - name: Build the page
        run: npm run build
      - name: Deploy to GitHub Pages
        run: |
          git config --global user.email "josecarlos.gonzalezvillegas1@lumen.com"
          git config --global user.name "josecarlosgonzalezv"
          npm run deploy
